version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.compose
    ports:
      - 8080:8080
    depends_on:
      - database
  database:
    image: postgres:14.4-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookystore
    volumes:
      - data:/var/lib/postgresql
volumes:
  data:
    external: false
