# Build stage
FROM maven:3.8.4-jdk-11-slim AS build
WORKDIR /app/source
COPY ./pom.xml ./pom.xml
RUN mvn verify --fail-never
COPY ./src ./src
RUN mvn clean package -Dmaven.test.skip -Pprod

# Package stage
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/source/target/*.jar ./app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
